name: My first workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4  
        # // otherwise dont work without actions ( no ls (on github -> action )
        # show so error on readme)
      - name: READ AND LIST FILES
        run: |
          echo "MY first workflow"
          ls -ltra
          cat README.md

      - name: GENERATE ASCII ARTWORK
        run: cowsay -f dragon "RUN FOR COVER , I AM DRAGON">>dragon.txt


# use | instead of 3 steps we do in 1 step
      # - name: List files
      #   run: ls

      # - name: Read README
      #   run: cat README.md